interface Arqueo {
  id : number
  supervisor: string
  nombres: string
  nombre_supervisor: string
  documento: number
  ip: number
  sucursal: number
  puntodeventa: number
  ventabruta: number
  baseefectivo: number
  totalingreso: number
  chancesabonados: number
  chancespreimpresos: number
  premiospagados: number
  efectivocajafuerte: number
  tirillarecaudo: number
  totalegresos: number
  totalbilletes: number
  totalmonedas: number
  totalarqueo: number
  sobrantefaltante: number
  canti_billete_cienmil1: number
  total_billete_cienmil1: number
  canti_billete_cincuentamil1: number
  total_billete_cincuentamil1: number
  canti_billete_veintemil1: number
  total_billete_veintemil1: number
  canti_billete_diezmil1: number
  total_billete_diezmil1: number
  canti_billete_cincomil1: number
  total_billete_cincomil1: number
  canti_billete_dosmil1: number
  total_billete_dosmil1: number
  canti_billete_mil1: number
  total_billete_mil1: number
  canti_moneda_mil1: number
  total_moneda_mil1: number
  canti_moneda_quinientos1: number
  total_moneda_quinientos1: number
  canti_moneda_docientos1: number
  total_moneda_docientos1: number
  canti_moneda_cien1: number
  total_moneda_cien1: number
  canti_moneda_cincuenta1: number
  total_moneda_ciencuenta1: number
  total_efectivo1: number
  total_premios_pagados1: number
  total: number
  
  canti_billete_cienmil: number
  total_billete_cienmil: number
  canti_billete_cincuentamil: number
  total_billete_cincuentamil: number
  canti_billete_veintemil: number
  total_billete_veintemil: number
  canti_billete_diezmil: number
  total_billete_diezmil: number
  canti_billete_cincomil: number
  total_billete_cincomil: number
  canti_billete_dosmil: number
  total_billete_dosmil: number
  canti_billete_mil: number
  total_billete_mil: number
  canti_moneda_mil: number
  total_moneda_mil: number
  canti_moneda_quinientos: number
  total_moneda_quinientos: number
  canti_moneda_docientos: number
  total_moneda_docientos: number
  canti_moneda_cien: number
  total_moneda_cien: number
  canti_moneda_cincuenta: number
  total_moneda_ciencuenta: number
  total_efectivo: number
  total_premios_pagados: number
  base_efectivos: number
  tirilla_recaudos: number
  entrega_colocador: number
  sobrantefaltante_caja: number
  colocador_cajafuerte: number
  rollos_bnet: number
  rollos_fisicos: number
  diferencia: number
  nombre_juego: number
  cantidad_bnet: number
  cantidad_fisicos: number
  cantidad_faltante: number
  cantidad_tiquete: number
  descargado: number
  nombre_juego2: number
  cantidad_bnet2: number
  cantidad_fisicos2: number
  cantidad_faltante2: number
  cantidad_tiquete2: number
  descargado2: number
  nombre_juego3: number
  cantidad_bnet3: number
  cantidad_fisicos3: number
  cantidad_faltante3: number
  cantidad_tiquete3: number
  descargado3: number
  nombre_juego4: number
  cantidad_bnet4: number
  cantidad_fisicos4: number
  cantidad_faltante4: number
  cantidad_tiquete4: number
  descargado4: number
  totaldescargados: number
  totalvalor: number
  requisito1: string
  observacion1: string
  requisito2: string
  observacion2: string
  requisito3: string
  observacion3: string
  requisito4: string
  observacion4: string
  requisito5: string
  observacion5: string
  requisito6: string
  observacion6: string
  requisito7: string
  observacion7: string
  requisito8: string
  observacion8: string
  requisito9: string
  observacion9: string
  requisito10: string
  observacion10: string
  requisito11: string
  observacion11: string
  requisito12: string
  observacion12: string
  requisito13: string
  observacion13: string
  requisito14: string
  observacion14: string
  requisito15: string
  observacion15: string
  requisito16: string
  observacion16: string
  requisito17: string
  observacion17: string
  requisito18: string
  observacion18: string
  requisito19: string
  observacion19: string
  requisito20: string
  observacion20: string
  requisito21: string
  observacion21: string
  requisito22: string
  observacion22: string
  requisito23: string
  observacion23: string
  requisito24: string
  observacion24: string
  requisito25: string
  observacion25: string
  requisito26: string
  observacion26: string
  requisito27: string
  observacion27: string
  requisito28: string
  observacion28: string
  requisito29: string
  requisito30: string
  imagen_observacion: Blob
  nombre_observacion: string
  firma_auditoria: Blob
  firma_colocadora: Blob
  fechavisita: string
  horavisita: string
  latitud: string
  longitud: string
}

export type Arqueos = Arqueo[]
